import React from 'react'
import "./Sep.css"

const Sep = () => {
  return (
    <div className='w-1359 border-solid border-black border-y overflow-hidden '>
      <div className=' mt-3 mb-3 whitespace-nowrap'>
        <div className="css-i4pl5u">
          <div className="font-semibold text-base inline">LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE</div>
          <div className="font-semibold text-base inline">LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE LOOKSRARE</div>
        </div>
      </div>

    </div>
  )
}

export default Sep